const cron = require('node-cron');
const { getConfig, isPaused, isBlocked } = require('../database/db');
const { isEnabled, scheduleFollowup, cancelFollowups, claimDueFollowups, completeFollowupAttempt, releaseFollowup, getCustomerSafeContext } = require('../supabase/client');
const TZ = 'America/Argentina/Buenos_Aires';
function parts(d) { return Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: TZ, year: 'numeric', month: '2-digit', day: '2-digit', weekday: 'short', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(d).map(p => [p.type, p.value])); }
function days() { return new Set((getConfig('cal_workdays') || '1,2,3,4,5,6').split(',').map(Number)); }
function weekday(d) { return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(parts(d).weekday); }
function localTime(d,h,m=0) { const p=parts(d); return new Date(`${p.year}-${p.month}-${p.day}T${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:00-03:00`); }
function withinBusinessHours(d) { const p=parts(d), w=weekday(d), m=+p.hour*60 + +p.minute; return days().has(w) && (w===6 ? m>=540&&m<780 : m>=495&&m<1035); }
function nextBusinessOpening(from, preferredHour=null) { let d=new Date(from); for(let i=0;i<10;i++){ const w=weekday(d); if(days().has(w)){ const c=localTime(d,preferredHour??(w===6?9:8),preferredHour==null&&w!==6?15:0); const close=localTime(d,w===6?13:17,w===6?0:15); if(c>from&&c<close)return c;} d=new Date(d.getTime()+86400000);} return new Date(from.getTime()+86400000); }
function firstRunAt(now=new Date()){const t=new Date(now.getTime()+10800000);return withinBusinessHours(t)?t:nextBusinessOpening(t);}
function secondRunAt(now=new Date()){return nextBusinessOpening(new Date(now.getTime()+43200000),10);}
function shouldFollowUp(text,kind='conversation'){return getConfig('followup_enabled')==='true'&&/[?¿]/.test(text||'')&&!['review','reminder','pickup'].includes(kind)&&!/(reseña|calific|retirar|turno (confirmado|agendado)|error técnico)/i.test(text);}
async function queueFollowup(contactKey,text,triggerKind='conversation'){if(!isEnabled()||!shouldFollowUp(text,triggerKind)||isPaused(contactKey)||isBlocked(contactKey))return null;const customer=await getCustomerSafeContext(contactKey);if(customer?.do_not_contact)return null;return scheduleFollowup({contactKey,nextRunAt:firstRunAt().toISOString(),triggerKind});}
function followupText(n){return n===1?'Hola, ¿pudiste ver mi mensaje anterior? Si querés, te ayudo a avanzar con la consulta o el turno.':'Te escribo una última vez por tu consulta. Si todavía necesitás ayuda, respondeme cuando quieras y seguimos desde ahí.';}
async function sendDueFollowups(){if(getConfig('followup_enabled')!=='true'||!isEnabled())return{sent:0};const rows=await claimDueFollowups();let sent=0;for(const row of rows){try{const customer=await getCustomerSafeContext(row.contact_key);if(customer?.do_not_contact||isPaused(row.recipient_address)||isBlocked(row.recipient_address)){await cancelFollowups(row.contact_key,'paused_blocked_or_opted_out');continue;}const attempt=+row.attempt_count+1,text=followupText(attempt);if(row.channel==='instagram'){const{sendInstagramMessage}=require('../instagram/instagram');await sendInstagramMessage(row.recipient_address.replace(/^ig:/,''),text);}else{const{sendMessage,getConnectionState}=require('../whatsapp/baileys');if(getConnectionState().status!=='connected')throw new Error('WhatsApp desconectado');await sendMessage(row.recipient_address,text);}await completeFollowupAttempt(row.id,attempt,attempt<2?secondRunAt().toISOString():null);sent++;}catch(err){const failures=+(row.send_failure_count||0)+1;await releaseFollowup(row.id,new Date(Date.now()+900000).toISOString(),err.message,failures);}}return{sent};}
function startFollowups(){cron.schedule('*/5 * * * *',()=>sendDueFollowups().catch(err=>console.error('[FOLLOWUP]',err.message)),{timezone:TZ});console.log('[FOLLOWUP] Seguimientos activos (máximo 2)');}
module.exports={startFollowups,sendDueFollowups,queueFollowup,shouldFollowUp,firstRunAt,secondRunAt,withinBusinessHours};
